name: tag and release 
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:

  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      id: get-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        VERBOSE: true

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get-tag.outputs.new_tag }}
